FROM debian:9-slim

RUN mkdir -p /build && \
    apt-get update && \
    apt-get install -y build-essential libpcre3-dev libssl-dev zlib1g-dev git && \
    apt-get install -y ruby ruby-dev rubygems && \
    gem install --no-ri --no-rdoc fpm && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /build
